networks:
  portable-media:
    external: true

services:
  frontend:
    build:
      context: ./frontend
    develop:
      watch:
        - path: ./frontend
          target: /app
          action: sync
    ports:
      - 3000:3000
    networks:
      - portable-media

  database:
    image: postgres:latest

    # Default postgres port
    ports:
      - 5432:5432
    networks:
      - portable-media

    # Ensure you have POSTGRES_USER and POSTGRES_PASSWORD entries in a .env file in the root of the directory alongside this file
    env_file: .env

    environment:
      POSTGRES_DB: portable-media

    volumes:
      # Persists database data between container rebuilds
      - ./db-data/:/var/lib/postgresql/data/
      # Initialization scripts for the database
      - ./db/init-scripts/:/docker-entrypoint-initdb.d

  backend:
    env_file: .env
    environment:
      ROCKET_ADDRESS: 0.0.0.0
      ROCKET_PORT: 8000
    build:
      context: ./backend
    develop:
      watch:
        - path: ./backend
          target: /app
          action: rebuild
    ports:
      - 8000:8000
    depends_on:
      - database
    networks:
      - portable-media
