[package]
name = "portable-media"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.1"
diesel = { version = "2.2.0", features = ["postgres"] }
dotenvy = "0.15"

[workspace]
members = [
  "api",
  "domain",
  "infrastructure",
  "application",
  "shared",
]
