import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import UserContextProvider from "./contexts/usercontext";

const ubuntu = Ubuntu({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "mrrp",
  description: "A Mega-Robust Rambling Platform generated by Jovie",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserContextProvider>
        <body
          className={`${ubuntu.className} antialiased flex flex-col items-center justify-center pt-20 gap-5 bg-background text-accent min-h-screen w-screen`}
        >
          {children}
        </body>
      </UserContextProvider>
    </html>
  );
}
